apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-test
  description: The test API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $openapi: https://github.com/pexa-tday/backstage-test/blob/main/test.yaml
